[package]

name = "gosu-rs"
version = "0.0.1"
authors = ["oliver"]

[lib]
name = "gosu"
path = "src/lib.rs"

[dependencies.gfx]
git = "http://github.com/gfx-rs/gfx-rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
